FROM python:3.10-slim


# install Java 17
RUN apt-get update && \
    apt-get install -y openjdk-17-jdk procps && \
    apt-get clean

# set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir --timeout=240 -r requirements.txt

COPY . .

CMD ["./entrypoint.sh"]

